# generated by fastapi-codegen:
#   filename:  ./ns-provision-openapi.yml
#   timestamp: 2024-01-16T21:00:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Namespace(BaseModel):
    id: Optional[str] = None


class NamespaceArray(BaseModel):
    __root__: List[Namespace]


class Provisioning(BaseModel):
    max_cpu: Optional[str] = None
    max_ram: Optional[str] = None
    max_storage: Optional[str] = None
    cluster: Optional[str] = None
    cod_prog: Optional[str] = None
    afqdn: Optional[List[str]] = None


class Cluster(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    csi: Optional[bool] = None
    production: Optional[bool] = None


class ClusterArray(BaseModel):
    __root__: List[Cluster]


class ProvisioningArray(BaseModel):
    __root__: List[Provisioning]
